### ISSUE TITLE
Dns?

### ISSUE THREAD

**Issue by zgelici** [Xstasy/pokemongo-stats-collector#1]
Hi,

I saw this in your readme:
There are two alternatives, one is changing the hosts file on your phone. On Android you can use Hosts Editor (ROOT) and on iOS you would need a jailbroken device to edit /etc/hosts.

what kind of dns i need to fill in the host?

dns?? / my ip

Thanks

**Comment by Xstasy** [comment]
You have to add a line to the /etc/hosts that looks like this.

your-server-ip			batch.upsight-api.com
